# Generated by Django 5.2.3 on 2025-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_reviews',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
